version: '3.8'

services:

  php-apache:
    build: ./docker/php
    volumes:
      - ./html:/var/www/html
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - TZ=${TZ}
    tty: true
